### ISSUE TITLE
No plots

### ISSUE THREAD

**Issue by honzapulpan** [zwicker-group/py-pde#32] opened 2020-11-16 16:52 UTC
Hi,

I'd like to try py-pde for some school projects, but I'm not able to make it plotting any results. This is the only thing I get, no error message, nothing. I pip installed py-pde, version is 0.12.1, all other packages are the latest ones.

One of examples in Jupyter Notebook:
<img width="325" alt="py-pde-noplot" src="https://user-images.githubusercontent.com/11267326/99282174-a749b200-2833-11eb-9f1a-1fb4b0377ad0.png">

In Jupyterlab I get extra: 
<pde.tools.plotting.PlotReference at 0x7feef0b071c0>

Seems like something is wrongly configured at my side, but I can't find what it is :-( Could you please help me with this?

Edit: It works fine in ipython.

**Comment by david-zwicker** [comment] 2020-11-16 18:22
Thank you for the report. This bug is likely being caused by `py-pde` trying to guess how to best plot figures, but it apparently gets it wrong. Could you please check which matplotlib backend your using by default? You can do this by running

```python
import matplotlib as mpl
mpl.get_backend()
```

As a quick workaround you might be able to force a figure to display by adding `action="show"` to the plot command, i.e., call `sol.plot(action="show")`.

**Comment by honzapulpan** [comment] 2020-11-16 18:37
This is my default matplotlib backend: module://ipykernel.pylab.backend_inline

Workaround is working fine. Thanks a lot!

**Comment by david-zwicker** [comment] 2020-11-18 19:11
I'm still really puzzled why you don't see any plot with the default settings, but I cannot reproduce the problem on my side. I hope the workaround works fine for now. I will close the issue, but you're welcome to reopen it when the problem persists.

**Closed by david-zwicker** 2020-11-18 19:11 UTC
